pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'my-node-app'
    }

    stages {
        stage("Clone the Repo") {
            steps {
                git branch: 'main', url: 'https://github.com/gowthamchi/Jala_projects.git'
            }
        }

        stage("Check Workspace Structure") {
            steps {
                sh 'ls -la'
            }
        }

    

        stage("Docker Registry Login") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh '''
                        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage("Build & Push Docker Image") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh '''
                        cd project1/app
                        docker build -t $DOCKER_USER/my-node-app .
                        
                    '''
                }
            }
        }
        stage("trivy scan"){
            steps{
                sh ' trivy image --exit-code 1 --severity CRITICAL,HIGH my-node-app:latest'
            }
        }
        stage("Build & Push Docker Image") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh '''
                       docker push $DOCKER_USER/my-node-app
                        
                    '''
                }
            }
        }


        stage("Run Docker Container") {
            steps {
                sh '''
                    docker rm -f gowtham-node-app-container || true
                    docker run -d -p 3000:3000 --name gowtham-node-app-container gowtham1198/my-node-app
                '''
            }
        }
    }
}
