pipeline {
    agent any

    stages {
        stage("Clone the Repo") {
            steps {
                git branch: 'main', url: 'https://github.com/gowthamchi/Jala_projects.git'
            }
        }

        stage("Check Workspace Structure") {
            steps {
                sh 'ls -la'
            }
        }


        stage("Docker registry){
              steps{
                  withCredentials([usernamePaassword(credentialsId: 'docker_cred',usernameVariable: 'DOCKER_USER',usernamePassword: 'DOCKER_PASSWORD')]){
                    sh '''
                      docker login -u $DOCKER_USER -P $DOCKER_PASSWORD
                
                      '''
                      
                  }
              }
        }
       stage("Build Docker Image") {
    steps {
        sh '''
        cd project1/app
        docker build -t $DOCKER_USER/my-node-app .
        docker push $DOCKER_USER/my-node-app
        '''
    }
}
        stage("Run Docker Container") {
            steps {
                sh '''
                docker rm -f gowtham-node-app-container || true
                docker run -d -p 3000:3000 --name gowtham-node-app-container my-node-app
                '''
            }
        }
    }
}
